parameters:
    kendrick.data_collector.template: "KendrickSymfonyDebugToolbarGit:DataCollector:collector"
    kendrick.data_collector.repository_commit_url: "#"

services:
    data_collector.datacollector_git:
        class: Kendrick\SymfonyDebugToolbarGit\DataCollector\GitDataCollector
        arguments: [%kendrick.data_collector.repository_commit_url%]
        tags:
          - { name: data_collector, template: %kendrick.data_collector.template%, id:"datacollector_git" }