language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - FRAMEWORK_BUNDLE="~2.3" TWIG_BUNDLE_VERSION="~2.0" TWIG_VERSION="~1.12"

before_script:
  - composer require symfony/framework-bundle:${FRAMEWORK_BUNDLE}
  - composer require symfony/twig-bundle:${TWIG_BUNDLE_VERSION}
  - composer require twig/twig:${TWIG_VERSION}